#!/bin/bash

dir=$(dirname -- "$(readlink -f "${BASH_SOURCE}")")
source $dir/../helpers

packages=(
  'node' # node.js
  'deno' # better node.js

  # lang servers
  'typescript-language-server' 
  'vscode-langservers-extracted'
)

header "Install brew packages"
brew_install ${packages[*]}

# eval $dir/configure
