#!/bin/bash

dir=$(dirname -- "$(readlink -f "${BASH_SOURCE}")")
source $dir/helpers


export NONINTERACTIVE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
brew_path="/home/linuxbrew/.linuxbrew"


if installed "apt-get"; then
  run "apt-get update"
  run "apt-get install -y build-essential procps curl file git rustup"

elif installed "yum"; then
  run "yum install -y procps-ng curl file git gcc rustup"

elif is_macos; then
  unset NONINTERACTIVE
  brew_path="/opt/homebrew"

else
  echo "Unsupported linux distribution"
  exit 1
fi


header "Installing brew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
if ! grep -q "brew shellenv" ~/.bashrc; then
  echo "eval \"\$($brew_path/bin/brew shellenv)\"" >> ~/.bashrc
fi
eval "$($brew_path/bin/brew shellenv)"

header "Installing packages"
eval $dir/add_pkg shell $*
