#!/bin/bash

set -e

unstyled="\033[0m"
header() { echo; echo -e "\033[1m\033[0;32m$1$unstyled"; }

run() { echo $1; eval $1; }

installed() { [ -x "$(command -v $1)" ]; }

is_macos() { [[ $OSTYPE == 'darwin'* ]]; }

is_docker() { [ -e /.dockerenv ]; }

brew_install() { run "brew install $*"; }

cargo_install() { run "cargo install --locked $*"; }

fish_home() { echo "$HOME/.config/fish"; }

add_fish_config() {
    local dir
    dir="$(fish_home)/conf.d/"
    mkdir -p "$dir"
    run "ln -sf $1 $dir"
}

add_fish_function() {
    local dir
    dir="$(fish_home)/functions/"
    mkdir -p "$dir"
    run "ln -sf $1 $dir"
}