#!/bin/bash

set -e

unstyled="\033[0m"
header() { echo; echo -e "\033[1m\033[0;32m$1$unstyled"; }

run() { echo $1; eval $1; }

installed() { [ -x "$(command -v $1)" ]; }

is_macos() { [[ $OSTYPE == 'darwin'* ]]; }

im_root() { [[ $EUID -eq 0 ]]; }

brew_install() { run "brew install $*"; }

cargo_install() { run "cargo install --locked $*"; }

update_apt() {
    if im_root; then
        run "apt update"
    else
        run "sudo apt update"
    fi
}

install_apt_packages() {
    if im_root; then
        run "apt install -y $*"
    else
        run "sudo apt install -y $*"
    fi
}

install_dnf_packages() {
    if im_root; then
        run "dnf -y install $*"
    else
        run "sudo dnf -y install $*"
    fi
}

fish_home() { echo "$HOME/.config/fish"; }

add_fish_config() {
    local dir
    dir="$(fish_home)/conf.d/"
    mkdir -p "$dir"
    run "ln -sf $1 $dir"
}

add_fish_function() {
    local dir
    dir="$(fish_home)/functions/"
    mkdir -p "$dir"
    run "ln -sf $1 $dir"
}

add_fish_completion() {
    local dir
    dir="$(fish_home)/completions/"
    mkdir -p "$dir"
    run "ln -sf $1 $dir"
}


run_installer() {
    temp_file=$(mktemp)
    pkg_manager=$(get_pkg_manager)
    eval "$1 $pkg_manager > $temp_file"
    source $temp_file
    rm $temp_file
}

get_pkg_manager() {
    if installed 'apt'; then
        echo 'apt'
    elif installed 'dnf'; then
        echo 'dnf'
    fi
}


ask_confirmation() {
    timeout=${2:-10}
    if command -v gum >/dev/null; then
        gum confirm "$1" --default=no --timeout=${timeout}s || return 1;
    else
        read -t $timeout -p "$1 (y/N): " answer
        if [[ $? -eq 0 ]]; then
            if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
                return 1;
            fi
        else
            return 1;
        fi
    fi
}


ask_input() {
    timeout=${2:-10}
    limit=${3:-100}
    local answer
    if command -v gum >/dev/null; then
        answer=$(gum input --placeholder="$1" --char-limit=$limit --timeout=${timeout}s);
    else
        read -t $timeout -p "$1: " answer
        if [[ $? -ne 0 ]]; then
            echo -e "\n\ntimed out" 1>&2
        fi
    fi
    echo $answer
}