#!/bin/bash

helpers_dir=$(dirname -- "$(readlink -f "${BASH_SOURCE}")")

set -e

header() { echo; echo -e "\033[1m\033[0;32m$1\033[0m"; }

run() { echo $1; eval $1; }

installed() { [ -x "$(command -v $1)" ]; }

sudo_prefix() { [[ $EUID -eq 0 ]] && echo "" || echo "sudo "; }

run_installer() {
    temp_file=$(mktemp)
    if installed 'apt'; then
        local pkg_manager='apt'
    elif installed 'dnf'; then
        local pkg_manager='dnf'
    fi
    eval "$1 $pkg_manager > $temp_file"
    source $temp_file
    rm $temp_file
}


ask_confirmation() {
    timeout=${2:-10}
    if command -v gum >/dev/null; then
        gum confirm "$1" --default=no --timeout=${timeout}s || return 1;
    else
        read -t $timeout -p "$1 (y/N): " answer
        if [[ $? -eq 0 ]]; then
            if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
                return 1;
            fi
        else
            return 1;
        fi
    fi
}


ask_input() {
    timeout=${2:-10}
    limit=${3:-100}
    local answer
    if command -v gum >/dev/null; then
        answer=$(gum input --placeholder="$1" --char-limit=$limit --timeout=${timeout}s);
    else
        read -t $timeout -p "$1: " answer
        if [[ $? -ne 0 ]]; then
            echo -e "\n\ntimed out" 1>&2
        fi
    fi
    echo $answer
}
