"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg_host)\
$os\
$username\
$hostname\
[](fg:color_bg_host bg:color_bg_dir)\
$directory\
[](fg:color_bg_dir bg:color_bg_vcs)\
$git_branch\
$git_status\
${custom.jj_status}\
[](fg:color_bg_vcs bg:color_bg_lang)\
$rust\
$dotnet\
$golang\
$nodejs\
$python\
[](fg:color_bg_lang bg:color_bg_env)\
$direnv\
${custom.tmux}\
$docker_context\
$conda\
[ ](bg:color_bg_env)\
[](fg:color_bg_env bg:color_bg_time)\
$time\
[](fg:color_bg_time)\
$line_break$character"""


palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_bg_host  = '#d65d0e'
color_bg_dir  = '#d79921'
color_bg_vcs   = '#689d6a'
color_bg_lang  = '#458588'
color_bg_time  = '#3c3836'
color_bg_env   = '#665c54'
color_fg_dark  = '#1b1914'
color_fg_light = '#fbf1c7'
color_fg_green = '#98971a'
color_fg_red   = '#cc241d'


[os]
disabled = false
style = "bg:color_bg_host fg:color_fg_dark"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
aliases = { "sergey" = "me" }
format = '[ $user ](fg:color_fg_dark bg:color_bg_host)'

[hostname]
ssh_only = true
format = "[@ $hostname ](fg:color_fg_dark bg:color_bg_host)"


# Directory

[directory]
format = "[ $path ](fg:color_fg_dark bg:color_bg_dir)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󰇚"
"Projects" = "󰲋 "


# VCS

[git_branch]
format = '[  $branch ](fg:color_fg_dark bg:color_bg_vcs)'

[git_status]
format = '[($all_status$ahead_behind )](fg:color_fg_dark bg:color_bg_vcs)'

[custom.jj_status]
when = "jj root --ignore-working-copy"
format = "[🥷 $output ](fg:color_fg_dark bg:color_bg_vcs)"
command = '''
jj log --ignore-working-copy -r@ -n1 --no-graph -T "" --stat | tail -n1 | \
sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" ' ${1}m ${2}+ ${3}-' | sd " 0." ""
'''

# Languages

[rust]
format = '[ ( $version) ](fg:color_fg_dark bg:color_bg_lang)'

[dotnet]
format = '[ 󰪮( $version) ](fg:color_fg_dark bg:color_bg_lang)'

[golang]
format = '[ 󰟓( $version) ](fg:color_fg_dark bg:color_bg_lang)'

[nodejs]
format = '[ 󰎙( $version) ](fg:color_fg_dark bg:color_bg_lang)'

[python]
format = '[ ( $version) ](fg:color_fg_dark bg:color_bg_lang)'


# Environment

[direnv]
disabled = false
format = '[ $loaded$allowed](fg:color_fg_light bg:color_bg_env)'
loaded_msg = "󱆄"
unloaded_msg =""
allowed_msg = ""
denied_msg = "󱦃"
not_allowed_msg = "󱦃"

[custom.tmux]
# when = "echo $TERM_PROGRAM | grep tmux"
when = "echo $TERM_PROGRAM | grep tmux && tmux show -g status | grep 'status off'"
format = "[ \\[$output\\]](fg:color_fg_light bg:color_bg_env)"
command = "tmux show automatic-rename | grep -q 'automatic-rename off' && tmux display-message -p '#S~#W###{window_index}' || tmux display-message -p '#S###{window_index}'"

[docker_context]
format = '[ ( $context)](fg:color_fg_light bg:color_bg_env)'

[conda]
format = '[ ( $environment)](fg:color_fg_light bg:color_bg_env)'


# Time

[time]
disabled = false
time_format = "%R"
format = '[  $time ](fg:color_fg_light bg:color_bg_time)'


# Prompt character

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[➜](fg:color_fg_green)'
error_symbol = '[](fg:color_fg_red)'
