inherits = "monokai_pro_octagon"

"ui.background" = { fg = "foreground" }

"ui.statusline" = { fg = "gruvbox-fg1", bg = "gruvbox-bg1" }
"ui.statusline.inactive" = { fg = "gruvbox-grey1", bg = "gruvbox-bg1" }
"ui.statusline.insert" = { fg = "gruvbox-bg0", bg = "gruvbox-green" }
"ui.statusline.normal" = { fg = "gruvbox-bg0", bg = "gruvbox-grey2" }
"ui.statusline.select" = { fg = "gruvbox-bg0", bg = "gruvbox-red" }

[palette]
gruvbox-fg1   = "#ddc7a1"
gruvbox-bg0   = "#282828"
gruvbox-bg1   = "#32302f"
gruvbox-grey1 = "#928374"
gruvbox-grey2 = "#a89984"
gruvbox-green = "#a9b665"
gruvbox-red   = "#ea6962"
