#!/bin/bash

dir=$(dirname -- "$(readlink -f "${BASH_SOURCE}")")
source $dir/../helpers

$dir/install.ts $(pkg_manager) | bash

bat_dir=$(bat --config-dir)
wget -P "$bat_dir/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme

source $dir/configure
