set -g status-position bottom
set -g prefix C-s
set -g mouse on

# fix terminal colors
set -g default-terminal "tmux-256color"
set -sa terminal-features ',xterm-256color:RGB'

# start window/pane numbering from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# automatically update titles
set -g set-titles on
set -g set-titles-string "#T"

# reload config
bind-key r source-file ~/.tmux.conf

# tmux plugins manager
set -g @plugin 'tmux-plugins/tpm'

# colored status bar with modules
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_background "default"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_modules_right "date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_date_time_text "%H:%M"

# fast copy from window - prefix + tab
set -g @plugin 'laktak/extrakto'
set -g @extrakto_filter_order "word quote s-quote line path"
set -g @extrakto_fzf_header "f g"

# quick menu for tmux management - prefix + q
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="q"
TMUX_FZF_OPTIONS="-p -w 95% -h 90% -m"

# select session or create new with dir from history
bind-key "C-x" run-shell "sesh connect \"$(
	sesh list | fzf-tmux -p 55%,60% \
		--no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash .)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""

# switch to last session: prefix + L
bind -N "last-session (via sesh) " L run-shell "sesh last"

# preserve current dir on open/split window
bind-key C-c new-window -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

# window/pane management
bind-key C-s select-pane -t :.+
bind-key C-a last-window
bind-key C-d next-window
bind-key C-e rotate-window

# hjkl
bind-key h split-window -v -c "#{pane_current_path}"
bind-key j split-window -h -c "#{pane_current_path}"
bind-key l split-window -h -c "#{pane_current_path}"
bind-key k split-window -v -c "#{pane_current_path}"
bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R

# remove kill window/pane confirmation but don't kill tmux
set -g detach-on-destroy off 
bind-key & kill-window
bind-key x kill-pane

# load plugins, this line should be last
source ~/.tmux/tmux.conf
